---
title: "MechaCarChallenge"
output: html_document
date: '2022-07-09'
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


```{r cars}
library(ggplot2)
library(tidyverse)
library(dbplyr)
```


```{r label=read_mpg echo=FALSE}
mecha_mpg <- data.frame(read.csv(file="MechaCar_mpg.csv"))
```

```{r}
head(mecha_mpg)
```

```{r}
model <- lm(mpg ~ AWD + ground_clearance + spoiler_angle + vehicle_weight + vehicle_length,data=mecha_mpg) #generate multiple linear regression model
model
```

```{r}
model
summary(model) #generate summary statistics
```
```{r}
suspension <- data.frame(read.csv(file="Suspension_Coil.csv"))
```

```{r}
head(suspension)
```

```{r}

total_summary  <-  summarize(suspension, mean=mean(suspension$PSI), median=median(suspension$PSI), variance=var(suspension$PSI), SD=sd(suspension$PSI))

total_summary
```

```{r}
by_susp <- suspension %>% group_by(Manufacturing_Lot)
psi_stats <- by_susp %>% summarize(mean=mean(PSI), median=median(PSI), variance=var(PSI), SD=sd(PSI))
lot_summary <- data.frame(psi_stats)
lot_summary
```

```{r}

```